apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
  labels:
    app: uptime-kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      containers:
      - name: uptime-kuma
        image: louislam/uptime-kuma:1
        ports:
        - containerPort: 3001
        livenessProbe:
          initialDelaySeconds: 2
          periodicSeconds: 5
          httpGet:
            path: /
            port: 3001

---

apiVersion: v1
kind: Service
metadata:
  namespace: uptime-kuma
  name: uptime-kuma
spec:
  selector:
    app.kubernetes.io/name: uptime-kuma
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3001


---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/use-port-in-redirects: "true"
spec:
  ingressClassName: uptime-kuma
  rules:
  - host: uptime.lab
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: uptime-kuma
            port:
              name: http
    host: uptime.lab
  tls:
  - hosts:
    - uptime.lab
    secretName: uptime-kuma-ingress-http

